# Selección de Predictores usando Estandarización

Un problema común al trabajar con datos numéricos es la diferencia de magnitudes.
<br>
Una forma de solucionar estos problemas es usando Estandarización o Escalar Predictores.
<br>
Estandarización: proceso de transformar los datos en una escala estandar.
<br>
    $ variableEstandarizada = \frac{x-\mu}{\sigma} $
<br>
donde: 
<br>
x: variable original
<br>
$\mu$: media de la variable original
<br>
$\sigma$: desviación estandad de la variable original
<br>
De esta forma obtendremos una distribución con media=0 y desviación_estandar=1

## Importar bibliotecas

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

from sklearn.linear_model import LinearRegression

## Datos

In [2]:
data = pd.read_csv('Multiple linear regression.csv')
data.head()

SAT   GPA  Rand 1,2,3
0  1714  2.40           1
1  1664  2.52           3
2  1760  2.54           3
3  1685  2.74           3
4  1693  2.83           2

In [3]:
data.describe()

SAT        GPA  Rand 1,2,3
count    84.000000  84.000000   84.000000
mean   1845.273810   3.330238    2.059524
std     104.530661   0.271617    0.855192
min    1634.000000   2.400000    1.000000
25%    1772.000000   3.190000    1.000000
50%    1846.000000   3.380000    2.000000
75%    1934.000000   3.502500    3.000000
max    2050.000000   3.810000    3.000000

## Construimos la regresión múltiple

### Variables dependiente e independiente

In [4]:
x = data[['SAT','Rand 1,2,3']]
y = data['GPA']

## Estandarización

In [5]:
from sklearn.preprocessing import StandardScaler

In [6]:
scaler = StandardScaler()

In [7]:
# Calcula la media y la desviación estandar
scaler.fit(x)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [8]:
# Aplica la transformación
x_scaled = scaler.transform(x)

In [16]:
x_scaled[:5]

array([[-1.26338288, -1.24637147],
       [-1.74458431,  1.10632974],
       [-0.82067757,  1.10632974],
       [-1.54247971,  1.10632974],
       [-1.46548748, -0.07002087]])

## Regresión con predictores escalados

In [11]:
reg = LinearRegression()
reg.fit(x_scaled,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [12]:
# Los coeficientes
reg.coef_

array([ 0.17181389, -0.00703007])

In [13]:
# La constante
reg.intercept_

3.330238095238095

## Tabla Resumen

In [14]:
reg_summary = pd.DataFrame([['Bias'],['SAT'],['Rand 1,2,3']], columns=['Features'])
reg_summary['Weights'] = reg.intercept_, reg.coef_[0], reg.coef_[1]

In [15]:
reg_summary

Features   Weights
0        Bias  3.330238
1         SAT  0.171814
2  Rand 1,2,3 -0.007030

### Interpretación

Mientras más cercano un peso a 0, es más pequeño su impacto.
Mientras más grande sea el peso, más grande su impacto.
La variable RAND no contribuye al modelo.

# Predicciones con pesos estandarizados

In [17]:
# Construimos un dataframe con 2 observaciones
new_data = pd.DataFrame(data=[[1700,2],[1800,1]],columns=['SAT','Rand 1,2,3'])
new_data

SAT  Rand 1,2,3
0  1700           2
1  1800           1

In [18]:
# Estos resultados no son validos
reg.predict(new_data)

array([295.39979563, 312.58821497])

In [19]:
# El modelo espera datos escalados
# Debemos transformar en dataframe de pruebas igual que el modelo de entrenamiento
# La información de la transformación esta enel objeto "scaler"
# asi que transformar las pruebas es facil
new_data_scaled = scaler.transform(new_data)
new_data_scaled

array([[-1.39811928, -0.07002087],
       [-0.43571643, -1.24637147]])

In [20]:
# Hacemos la predicción con los datos escalados
reg.predict(new_data_scaled)

array([3.09051403, 3.26413803])

## Y si quitaramos la variable RAND?

In [21]:
# Si eliminamos una variable con poco peso el resultado deberia ser el mismo.
reg_simple = LinearRegression()

# Convertimos la entrada en una matriz
x_simple_matrix = x_scaled[:,0].reshape(-1,1)

# Hacemos la regresión
reg_simple.fit(x_simple_matrix,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [22]:
# Hacemos la prediccion sobre la primera columna de los datos escalados
reg_simple.predict(new_data_scaled[:,0].reshape(-1,1))

array([3.08970998, 3.25527879])